openapi: 3.0.1
info:
  title: AA1 API
  description: API de gestión de clínicas, máquinas, técnicos, tickets y repuestos
  version: 1.0.0

servers:
  - url: http://localhost:8080

paths:

  # ===================== CLINICS =====================

  /clinics:
    get:
      summary: Obtener todas las clínicas
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ClinicOutDto'
    post:
      summary: Crear una clínica
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Clinic'
      responses:
        '201':
          description: Clínica creada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Clinic'
        '400':
          description: Error de validación
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'

  /clinics/{id}:
    get:
      summary: Obtener clínica por ID
      parameters:
        - $ref: '#/components/parameters/IdPath'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClinicDto'
        '404':
          description: Clínica no encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
    put:
      summary: Modificar clínica (completa)
      parameters:
        - $ref: '#/components/parameters/IdPath'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Clinic'
      responses:
        '200':
          description: Clínica actualizada
    patch:
      summary: Modificar clínica parcialmente
      parameters:
        - $ref: '#/components/parameters/IdPath'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClinicPatchDto'
      responses:
        '200':
          description: Clínica actualizada parcialmente
    delete:
      summary: Eliminar clínica
      parameters:
        - $ref: '#/components/parameters/IdPath'
      responses:
        '204':
          description: Eliminada correctamente

  # ===================== MACHINES =====================

  /machines:
    get:
      summary: Obtener máquinas
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Machine'
    post:
      summary: Crear máquina
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Machine'
      responses:
        '201':
          description: Máquina creada

  /machines/{id}:
    get:
      summary: Obtener máquina por ID
      parameters:
        - $ref: '#/components/parameters/IdPath'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Machine'
        '404':
          description: No encontrada
    put:
      summary: Modificar máquina
      parameters:
        - $ref: '#/components/parameters/IdPath'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Machine'
      responses:
        '200':
          description: Actualizada
    patch:
      summary: Modificar máquina parcialmente
      parameters:
        - $ref: '#/components/parameters/IdPath'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MachinePatchDto'
      responses:
        '200':
          description: Actualizada parcialmente
    delete:
      summary: Eliminar máquina
      parameters:
        - $ref: '#/components/parameters/IdPath'
      responses:
        '204':
          description: Eliminada

  # ===================== TECHNICIANS =====================

  /technicians:
    get:
      summary: Obtener técnicos
      responses:
        '200':
          description: OK
    post:
      summary: Crear técnico
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Technician'
      responses:
        '201':
          description: Técnico creado

  /technicians/{id}:
    get:
      summary: Obtener técnico por ID
      parameters:
        - $ref: '#/components/parameters/IdPath'
      responses:
        '200':
          description: OK
        '404':
          description: No encontrado
    put:
      summary: Modificar técnico
      parameters:
        - $ref: '#/components/parameters/IdPath'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Technician'
      responses:
        '200':
          description: Actualizado
    patch:
      summary: Modificar técnico parcialmente
      parameters:
        - $ref: '#/components/parameters/IdPath'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TechnicianPatchDto'
      responses:
        '200':
          description: Actualizado parcialmente
    delete:
      summary: Eliminar técnico
      parameters:
        - $ref: '#/components/parameters/IdPath'
      responses:
        '204':
          description: Eliminado

  # ===================== TICKETS (CON DTO) =====================

  /tickets:
    get:
      summary: Obtener tickets
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TicketOutDto'
    post:
      summary: Crear ticket
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TicketDto'
      responses:
        '201':
          description: Ticket creado

  /tickets/{id}:
    get:
      summary: Obtener ticket por ID
      parameters:
        - $ref: '#/components/parameters/IdPath'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TicketDto'
        '404':
          description: Ticket no encontrado
    put:
      summary: Modificar ticket
      parameters:
        - $ref: '#/components/parameters/IdPath'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TicketDto'
      responses:
        '200':
          description: Ticket actualizado
    patch:
      summary: Modificar ticket parcialmente
      parameters:
        - $ref: '#/components/parameters/IdPath'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TicketPatchDto'
      responses:
        '200':
          description: Ticket actualizado parcialmente
    delete:
      summary: Eliminar ticket
      parameters:
        - $ref: '#/components/parameters/IdPath'
      responses:
        '204':
          description: Eliminado

# ===================== COMPONENTS =====================

components:

  parameters:
    IdPath:
      name: id
      in: path
      required: true
      schema:
        type: integer
        format: int64

  schemas:

    # ----- CLINIC -----

    Clinic:
      type: object
      required: [name]
      properties:
        id: { type: integer, format: int64 }
        name: { type: string }
        address: { type: string }
        phone: { type: string }
        email: { type: string }

    ClinicDto:
      type: object
      properties:
        id: { type: integer, format: int64 }
        name: { type: string }
        address: { type: string }

    ClinicOutDto:
      type: object
      properties:
        id: { type: integer, format: int64 }
        name: { type: string }

    ClinicPatchDto:
      type: object
      properties:
        name: { type: string }
        address: { type: string }
        phone: { type: string }
        email: { type: string }

    # ----- MACHINE -----

    Machine:
      type: object
      required: [serialNumber, model, manufacturer]
      properties:
        id: { type: integer, format: int64 }
        serialNumber: { type: string }
        model: { type: string }
        manufacturer: { type: string }

    MachinePatchDto:
      type: object
      properties:
        serialNumber: { type: string }
        model: { type: string }
        manufacturer: { type: string }

    # ----- TECHNICIAN -----

    Technician:
      type: object
      required: [name, surname, email]
      properties:
        id: { type: integer, format: int64 }
        name: { type: string }
        surname: { type: string }
        email: { type: string }
        phone: { type: string }
        active: { type: boolean }

    TechnicianPatchDto:
      type: object
      properties:
        name: { type: string }
        surname: { type: string }
        email: { type: string }
        phone: { type: string }
        active: { type: boolean }

    # ----- TICKET DTOs -----

    TicketDto:
      type: object
      required: [description, openDate, status, machineId, technicianId]
      properties:
        description: { type: string }
        openDate: { type: string, format: date }
        closeDate: { type: string, format: date }
        status: { type: string }
        machineId: { type: integer, format: int64 }
        technicianId: { type: integer, format: int64 }

    TicketOutDto:
      type: object
      properties:
        id: { type: integer, format: int64 }
        description: { type: string }
        openDate: { type: string, format: date }
        closeDate: { type: string, format: date }
        status: { type: string }
        machineId: { type: integer, format: int64 }
        machineModel: { type: string }
        technicianId: { type: integer, format: int64 }
        technicianName: { type: string }

    TicketPatchDto:
      type: object
      properties:
        description: { type: string }
        closeDate: { type: string, format: date }
        status: { type: string }
        machineId: { type: integer, format: int64 }
        technicianId: { type: integer, format: int64 }

    # ----- ERRORS -----

    ErrorResponse:
      type: object
      properties:
        code: { type: integer }
        title: { type: string }
        message: { type: string }

    BadRequest:
      allOf:
        - $ref: '#/components/schemas/ErrorResponse'

    NotFound:
      allOf:
        - $ref: '#/components/schemas/ErrorResponse'
