openapi: 3.0.3
info:
  title: AA1 - API Gestión de Clínicas y Mantenimiento
  description: API REST para la gestión de clínicas, máquinas, técnicos, repuestos y tickets.
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Servidor local

paths:


  # CLINICS

  /clinics:
    get:
      summary: Obtener clínicas con filtros
      parameters:
        - in: query
          name: name
          schema: { type: string }
        - in: query
          name: address
          schema: { type: string }
        - in: query
          name: phone
          schema: { type: string }
      responses:
        "200":
          description: Lista de clínicas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ClinicOutDto"
        "500":
          description: Error interno

    post:
      summary: Crear clínica
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Clinic"
      responses:
        "201":
          description: Clínica creada
        "400":
          description: Error de validación

  /clinics/{id}:
    get:
      summary: Obtener clínica por ID
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      responses:
        "200":
          description: Clínica encontrada
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClinicDto"
        "404":
          description: Clínica no encontrada

    put:
      summary: Modificar clínica
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Clinic"
      responses:
        "200":
          description: Clínica modificada
        "404":
          description: Clínica no encontrada

    patch:
      summary: Modificar parcialmente clínica
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: Clínica actualizada
        "404":
          description: Clínica no encontrada

    delete:
      summary: Eliminar clínica
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      responses:
        "204":
          description: Clínica eliminada
        "404":
          description: Clínica no encontrada


  # MACHINES

  /machines:
    get:
      summary: Obtener máquinas con filtros
      parameters:
        - in: query
          name: serialNumber
          schema: { type: string }
        - in: query
          name: model
          schema: { type: string }
        - in: query
          name: manufacturer
          schema: { type: string }
      responses:
        "200":
          description: Lista de máquinas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Machine"

    post:
      summary: Crear máquina
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Machine"
      responses:
        "201":
          description: Máquina creada
        "400":
          description: Error de validación

  /machines/{id}:
    get:
      summary: Obtener máquina por ID
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      responses:
        "200":
          description: Máquina encontrada
        "404":
          description: Máquina no encontrada

    put:
      summary: Modificar máquina
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Machine"
      responses:
        "200":
          description: Máquina modificada
        "404":
          description: Máquina no encontrada

    patch:
      summary: Modificar parcialmente máquina
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: Máquina actualizada
        "404":
          description: Máquina no encontrada

    delete:
      summary: Eliminar máquina
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      responses:
        "204":
          description: Máquina eliminada
        "404":
          description: Máquina no encontrada

  /machines/by-clinic/{clinicId}:
    get:
      summary: Obtener máquinas por clínica (JPQL)
      parameters:
        - in: path
          name: clinicId
          required: true
          schema: { type: integer }
      responses:
        "200":
          description: Máquinas de la clínica
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Machine"


  # SPARE PARTS

  /spare-parts:
    get:
      summary: Obtener repuestos con filtros
      parameters:
        - in: query
          name: name
          schema: { type: string }
        - in: query
          name: manufacturer
          schema: { type: string }
        - in: query
          name: price
          schema: { type: number }
      responses:
        "200":
          description: Lista de repuestos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/SparePart"

    post:
      summary: Crear repuesto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SparePart"
      responses:
        "201":
          description: Repuesto creado
        "400":
          description: Error de validación

  /spare-parts/{id}:
    get:
      summary: Obtener repuesto por ID
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      responses:
        "200":
          description: Repuesto encontrado
        "404":
          description: Repuesto no encontrado

    put:
      summary: Modificar repuesto
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SparePart"
      responses:
        "200":
          description: Repuesto modificado
        "404":
          description: Repuesto no encontrado

    patch:
      summary: Modificar parcialmente repuesto
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: Repuesto actualizado
        "404":
          description: Repuesto no encontrado

    delete:
      summary: Eliminar repuesto
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      responses:
        "204":
          description: Repuesto eliminado
        "404":
          description: Repuesto no encontrado


  # TECHNICIANS

  /technicians:
    get:
      summary: Obtener técnicos con filtros
      parameters:
        - in: query
          name: name
          schema: { type: string }
        - in: query
          name: email
          schema: { type: string }
        - in: query
          name: active
          schema: { type: boolean }
      responses:
        "200":
          description: Lista de técnicos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Technician"

    post:
      summary: Crear técnico
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Technician"
      responses:
        "201":
          description: Técnico creado
        "400":
          description: Error de validación

  /technicians/{id}:
    get:
      summary: Obtener técnico por ID
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      responses:
        "200":
          description: Técnico encontrado
        "404":
          description: Técnico no encontrado

    put:
      summary: Modificar técnico
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Technician"
      responses:
        "200":
          description: Técnico modificado
        "404":
          description: Técnico no encontrado

    patch:
      summary: Modificar parcialmente técnico
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: Técnico actualizado
        "404":
          description: Técnico no encontrado

    delete:
      summary: Eliminar técnico
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      responses:
        "204":
          description: Técnico eliminado
        "404":
          description: Técnico no encontrado

  /technicians/by-active/{active}:
    get:
      summary: Obtener técnicos activos o inactivos (JPQL)
      parameters:
        - in: path
          name: active
          required: true
          schema: { type: boolean }
      responses:
        "200":
          description: Técnicos filtrados
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Technician"


  # TICKETS

  /tickets:
    get:
      summary: Obtener tickets con filtros
      parameters:
        - in: query
          name: status
          schema: { type: string }
        - in: query
          name: machineId
          schema: { type: integer }
        - in: query
          name: technicianId
          schema: { type: integer }
      responses:
        "200":
          description: Lista de tickets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TicketOutDto"

    post:
      summary: Crear ticket
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Ticket"
      responses:
        "201":
          description: Ticket creado
        "400":
          description: Error de validación

  /tickets/{id}:
    get:
      summary: Obtener ticket por ID
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      responses:
        "200":
          description: Ticket encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TicketDto"
        "404":
          description: Ticket no encontrado

    put:
      summary: Modificar ticket
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Ticket"
      responses:
        "200":
          description: Ticket modificado
        "404":
          description: Ticket no encontrado

    patch:
      summary: Modificar parcialmente ticket
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: Ticket actualizado
        "404":
          description: Ticket no encontrado

    delete:
      summary: Eliminar ticket
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      responses:
        "204":
          description: Ticket eliminado
        "404":
          description: Ticket no encontrado

  /tickets/jpql/by-status:
    get:
      summary: Obtener tickets por estado (JPQL)
      parameters:
        - in: query
          name: status
          required: true
          schema: { type: string }
      responses:
        "200":
          description: Tickets filtrados
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TicketOutDto"

components:
  schemas:

    Clinic:
      type: object
      required: [name]
      properties:
        id: { type: integer }
        name: { type: string }
        address: { type: string }
        phone: { type: string }
        email: { type: string }

    ClinicDto:
      type: object
      properties:
        id: { type: integer }
        name: { type: string }
        address: { type: string }

    ClinicOutDto:
      type: object
      properties:
        id: { type: integer }
        name: { type: string }

    Machine:
      type: object
      required: [serialNumber, model, manufacturer]
      properties:
        id: { type: integer }
        serialNumber: { type: string }
        model: { type: string }
        manufacturer: { type: string }

    SparePart:
      type: object
      required: [name, serialNumber, manufacturer, price, stock]
      properties:
        id: { type: integer }
        name: { type: string }
        serialNumber: { type: string }
        manufacturer: { type: string }
        price: { type: number }
        stock: { type: integer }

    Technician:
      type: object
      required: [name, surname, email]
      properties:
        id: { type: integer }
        name: { type: string }
        surname: { type: string }
        email: { type: string }
        phone: { type: string }
        active: { type: boolean }

    Ticket:
      type: object
      required: [description, openDate, status]
      properties:
        id: { type: integer }
        description: { type: string }
        openDate: { type: string, format: date }
        closeDate: { type: string, format: date }
        status: { type: string }

    TicketDto:
      type: object
      properties:
        id: { type: integer }
        description: { type: string }
        openDate: { type: string, format: date }
        closeDate: { type: string, format: date }
        status: { type: string }
        machineId: { type: integer }
        technicianId: { type: integer }

    TicketOutDto:
      type: object
      properties:
        id: { type: integer }
        description: { type: string }
        status: { type: string }
        openDate: { type: string, format: date }
        closeDate: { type: string, format: date }
        machineId: { type: integer }
        machineModel: { type: string }
        technicianId: { type: integer }
        technicianName: { type: string }
