spring.datasource.url=jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:aa1}?allowPublicKeyRetrieval=true&useSSL=false&authenticationPlugins=org.mariadb.jdbc.plugin.authentication.standard.NativePasswordPlugin
spring.datasource.username=${DB_USER:aa1}
spring.datasource.password=${DB_PASSWORD:aa1}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect